# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piston', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('canceled', 'Canceled'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='token',
            name='timestamp',
            field=models.IntegerField(default=1521579914),
        ),
    ]
